spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

