spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: # set your mongodb url here mongodb://username:password@localhost:27017/yourDB
      database: product-service
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

